# Generated by Django 4.0.2 on 2022-03-06 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ticket', '0002_ticket_current_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='error',
            new_name='status',
        ),
    ]
