# Generated by Django 4.0.2 on 2022-03-06 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ticket', '0004_rename_project_name_ticket_price_ticket_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Booked', 'Booked')], max_length=200, null=True),
        ),
    ]
